/*
 * This file was automatically generated by EvoSuite
 * Mon Jul 18 15:17:05 GMT 2016
 */

package org.objectweb.cjdbc.common.exceptions;

import org.junit.Test;
import static xcorpus.AssertionAdapter.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.mock.java.lang.MockThrowable;
import org.junit.runner.RunWith;
import org.objectweb.cjdbc.common.exceptions.BadConnectionException;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true) 
public class BadConnectionException_ESTest extends BadConnectionException_ESTest_scaffolding {

  //Test case number: 0
  /*
   * 2 covered goals:
   * Goal 1. org.objectweb.cjdbc.common.exceptions.BadConnectionException.<init>(Ljava/lang/Throwable;)V: root-Branch
   * Goal 2. org.objectweb.cjdbc.common.exceptions.BadConnectionException.<init>(Ljava/lang/String;Ljava/lang/Throwable;)V: root-Branch
   */

	@Test(timeout=300000)
  public void test0()  throws Throwable  {
      MockThrowable mockThrowable0 = new MockThrowable((String) null);
      BadConnectionException badConnectionException0 = new BadConnectionException((Throwable) mockThrowable0);
      BadConnectionException badConnectionException1 = new BadConnectionException("", (Throwable) badConnectionException0);
      assertFalse(badConnectionException1.equals((Object)badConnectionException0));
  }
}
